# Generated by Django 6.0.5 on 2026-06-19 17:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_pedido_base_pedido_iva_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio al momento de la venta', max_digits=10),
        ),
    ]
