# Generated by Django 6.0.5 on 2026-05-28 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etapa', models.CharField(choices=[('PROSPECCION', 'Prospección'), ('PROPUESTA', 'Propuesta'), ('NEGOCIACION', 'Negociación'), ('CERRADA_GANADA', 'Cerrada Ganada'), ('CERRADA_PERDIDA', 'Cerrada Perdida')], max_length=20)),
                ('fecha_cierre', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.cliente')),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
            },
        ),
    ]
