# Generated by Django 6.0.5 on 2026-06-20 15:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_stock'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oportunidad',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Oportunidad', 'verbose_name_plural': 'Oportunidades'},
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 20, 15, 15, 55, 165015, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='oportunidades', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='etapa',
            field=models.CharField(choices=[('PRO', 'Prospección'), ('PRP', 'Propuesta'), ('NEG', 'Negociación'), ('GAN', 'Cerrada Ganada'), ('PER', 'Cerrada Perdida')], default='PRO', max_length=3),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
